lexik_jwt_authentication:
  secret_key: "%kernel.project_dir%/config/jwt/private.pem" # clé privée pour la signature
  public_key: "%kernel.project_dir%/config/jwt/public.pem" # clé publique pour la vérification
  pass_phrase: "%env(JWT_PASSPHRASE)%" # passphrase si vous avez chiffré la clé
  token_ttl: 3600
